stages:
  split_data:
    cmd: python src/data/split_data.py
    deps:
      - src/data/split_data.py
      - data/raw_data/raw.csv
    params:
      - split
    outs:
      - data/processed_data/X_train.csv
      - data/processed_data/X_test.csv
      - data/processed_data/y_train.csv
      - data/processed_data/y_test.csv

  normalize_data:
    cmd: python src/data/normalize_data.py
    deps:
      - src/data/normalize_data.py
      - data/processed_data/X_train.csv
      - data/processed_data/X_test.csv
    params:
      - scaling
    outs:
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/X_test_scaled.csv

  gridsearch:
    cmd: python src/models/gridsearch.py
    deps:
      - src/models/gridsearch.py
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/y_train.csv
    params:
      - model
    outs:
      - models/best_params.pkl

  train_model:
    cmd: python src/models/train_model.py
    deps:
      - src/models/train_model.py
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/y_train.csv
      - models/best_params.pkl
    params:
      - model
    outs:
      - models/model.pkl

  evaluate_model:
    cmd: python src/models/evaluate_model.py
    deps:
      - src/models/evaluate_model.py
      - data/processed_data/X_test_scaled.csv
      - data/processed_data/y_test.csv
      - models/model.pkl
    outs:
      - data/processed_data/predictions.csv
    metrics:
      - metrics/scores.json

