split:
  test_size: 0.2
  random_state: 42

scaling:
  method: standard  # could extend later (minmax, robust, etc.)

model:
  type: RandomForestRegressor
  random_state: 42
  grid_params:
    n_estimators: [50, 100, 200]
    max_depth: [5, 10, null, 20]

